#!/bin/sh
# Run each test and compare
# against known good output

dodiff=0;

if [ "$#" -ge 1 ]
then if [ "$1" == "-d" ]
     then dodiff=1;
     fi
fi

# Make all the tests
make > /dev/null 2> /dev/null

# Try to use each input source file
for i in test*.c
do
  # Print the test name
  b=$(basename $i .c)
  echo -n $i

  # Run the test with some arguments, capture the output
  emu6809 $b -l -foo file1 file2 > testout 2> /dev/null

  if [ ! -f "out/$b" ]
  then echo " has no output file to compare against"
       rm -f testout $b
       continue
  fi

  # Compare this agains the correct output
  cmp -s "out/$b" testout

  # If different, announce failure
  # and print out the difference
  if [ "$?" -eq "1" ]
  then echo ": failed"
       if [ $dodiff -eq 1 ]
       then diff -c "out/$b" testout
       else echo
       fi

  # No failure, so announce success
  else echo ": OK"
  fi

  # Remove the test and the output
  rm -f testout $b
done

# Clean up
make clean > /dev/null 2> /dev/null
